version: "2.1"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    links:
      - redis
      - minio
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    working_dir: /backend
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - ./frontend:/frontend
    environment:
      - API_HOST=backend
      - CHOKIDAR_USEPOLLING=true
    working_dir: /frontend
    healthcheck:
      test: "exit 0"
    depends_on:
      - backend

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
  
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - data:/data
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
      MINIO_REGION: ap-northeast-1

volumes:
  data: